Meta Data

(1 = male; 0 = female)
id (Unique id for each patient)
age (Age of the patient in years)
origin (place of study)
sex (Male/Female)
cp chest pain type ([typical angina, atypical angina, non-anginal, asymptomatic])
trestbps resting blood pressure (resting blood pressure (in mm Hg on admission to the hospital))
chol (serum cholesterol in mg/dl)
fbs (if fasting blood sugar > 120 mg/dl)
restecg (resting electrocardiographic results)
-- Values: [normal, stt abnormality, lv hypertrophy]
thalach: maximum heart rate achieved
exang: exercise-induced angina (True/ False)
old-peak: ST depression induced by exercise relative to rest
slope: the slope of the peak exercise ST segment
ca: number of major vessels (0-3) colored by fluoroscopy
thal: [normal; fixed defect; reversible defect]
num: the predicted attribute

Import Packages

In [1]:
import numpy as np
import pandas as pd
import warnings
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split as tt
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

Reading csv file

In [2]:
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

Splitting data into features and labels, and train test split

In [3]:
m = df.drop(["target"],axis=1)
n = df["target"]

m_train,m_test,n_train,n_test = tt(m,n,train_size=0.78,stratify=n,random_state=0)

Fitting data into Logistic Regression Model

In [4]:
log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(m_train,n_train)

n_train_pred = log_reg.predict(m_train)
n_test_pred = log_reg.predict(m_test)

Calculate the accuracy for the training and testing data

In [5]:
acc_train = accuracy_score(n_train,n_train_pred)
acc_test = accuracy_score(n_test,n_test_pred)
print("Training Data Accuracy:",acc_train)
print("Testing Data Accuracy:",acc_test)

Training Data Accuracy: 0.853566958698373
Testing Data Accuracy: 0.8230088495575221

Predictions with user defined inputs

In [6]:
ip = np.array((43,0,1,118,210,0,1,192,0,0.7,2,0,2))
ip = ip.reshape(1,-1)
pred = log_reg.predict(ip)

if pred==1:
    print("Defective Heart")
else:
    print("Healthy Heart")

Defective Heart