Import Packages

In [1]:
import numpy as np
import pandas as pd
import warnings
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
# from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split as tt
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

Reading csv file

In [3]:
df = pd.read_csv('heart.csv')
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

Splitting data into features and labels, and train test split

In [4]:
m = df.drop(["target"],axis=1)
n = df["target"]

m_train,m_test,n_train,n_test = tt(m,n,train_size=0.78,stratify=n,random_state=0)

List of Models

In [5]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

def compare_models_train_test():
    for model in models:
        # training the model
        model.fit(m_train, n_train)
        # evaluating the model
        n_test_pred = model.predict(m_test)
        accuracy = accuracy_score(n_test, n_test_pred)
        print('Accuracy score of the ', model, ' = ', accuracy)


compare_models_train_test()
print("\n")

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.8230088495575221
Accuracy score of the  SVC(kernel='linear')  =  0.831858407079646
Accuracy score of the  KNeighborsClassifier()  =  0.7345132743362832
Accuracy score of the  RandomForestClassifier()  =  1.0

Cross Validation

In [6]:
def compare_models_cross_validation():
    for model in models:
        cv_score = cross_val_score(model, m, n,cv=5)
        mean_accuracy = sum(cv_score) / len(cv_score)
        mean_accuracy = mean_accuracy * 100
        mean_accuracy = round(mean_accuracy, 2)

        print('Cross Validation accuracies for ', model, '=  ', cv_score)
        print('Accuracy % of the ', model, mean_accuracy)
        print('----------------------------------------------')

compare_models_cross_validation()

Cross Validation accuracies for  LogisticRegression(max_iter=1000) =   [0.88292683 0.85853659 0.87804878 0.82439024 0.80487805]
Accuracy % of the  LogisticRegression(max_iter=1000) 84.98
----------------------------------------------
Cross Validation accuracies for  SVC(kernel='linear') =   [0.88292683 0.86829268 0.84390244 0.81463415 0.80487805]
Accuracy % of the  SVC(kernel='linear') 84.29
----------------------------------------------
Cross Validation accuracies for  KNeighborsClassifier() =   [0.76585366 0.74634146 0.76097561 0.71219512 0.75121951]
Accuracy % of the  KNeighborsClassifier() 74.73
----------------------------------------------
Cross Validation accuracies for  RandomForestClassifier() =   [1.         1.         1.         1.         0.98536585]
Accuracy % of the  RandomForestClassifier() 99.71
----------------------------------------------