Import Packages

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix,r2_score
from sklearn.model_selection import train_test_split as tt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression
import warnings

warnings.filterwarnings("ignore")

Reading csv files

In [3]:
df_portuguese = pd.read_csv("student_data/student-por.csv",delimiter=";")
df_math = pd.read_csv("student_data/student-mat.csv",delimiter=";")

df = pd.concat([df_portuguese,df_math],axis=0)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

Data Processing and Mapping

In [4]:
# Only portuguese grades
# Data Processing and Mapping
col = list(df.columns)
# print(df.head())
# df["G1"] = df["G1"].astype("int64")
# df["G2"] = df["G2"].astype("int64")

# Data Processing
c = list(df_portuguese.columns)
y = []
g = []
for i in range(len(c)):
    if df_portuguese[c[i]].dtype == "object":
        g.append(c[i])
        l = df_portuguese[c[i]].unique()
        y.append(l)

# Label Mapping
ma = {}
for i in range(len(y)):
    o = {}
    for j in range(len(y[i])):
        o[y[i][j]] = j
        df_portuguese.replace({g[i]:{y[i][j]:j}},inplace=True)
    ma[g[i]] = o

# # Data Processing
# c = list(df.columns)
# y = []
# g = []
# for i in range(len(c)):
#     if df[c[i]].dtype == "object":
#         g.append(c[i])
#         l = df[c[i]].unique()
#         y.append(l)
#
# # Label Mapping
# ma = {}
# for i in range(len(y)):
#     o = {}
#     for j in range(len(y[i])):
#         o[y[i][j]] = j
#         df.replace({g[i]:{y[i][j]:j}},inplace=True)
#     ma[g[i]] = o
# print(ma)
# print(ma["reason"]["home"])

# # Data Processing made simple use Label Encoder
# le = LabelEncoder()
# c = list(df.columns)
# for i in range(len(c)):
#     if df[c[i]].dtype == "object":
#         df[c[i]] = le.fit_transform(df[c[i]])
#
# print(df)

# df_portuguese=df_portuguese.drop(["address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","guardian"],axis=1)
# df = df.drop(["address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","guardian"],axis=1)
m = df_portuguese.drop("G3",axis=1)
n = df_portuguese["G3"]
# m = df.drop("G3",axis=1)
# n = df["G3"]

Splitting data into training and testing data

In [5]:
m_train,m_test,n_train,n_test = tt(m,n,train_size=0.78,random_state=0)

Fitting data into Linear Regression Model

In [6]:
clf = LinearRegression()
clf.fit(m_train,n_train)

n_train_pred = clf.predict(m_train)
n_test_pred = clf.predict(m_test)

Calculate the r squared error for both training and test data

In [7]:
train_error = r2_score(n_train,n_train_pred)
test_error = r2_score(n_train,n_train_pred)
print(train_error)
print(test_error)

0.8552704829584191
0.8552704829584191

Predict user defined inputs

In [9]:
ip = np.array((ma[g[0]]["GP"],ma[g[1]]["F"],15,ma[g[2]]["U"],ma[g[3]]["GT3"],ma[g[4]]["T"],2,1,ma[g[5]]["services"],
               ma[g[6]]["other"],ma[g[7]]["reputation"],ma[g[8]]["father"],3,3,0,ma[g[9]]["no"],ma[g[10]]["yes"],
               ma[g[11]]["no"],ma[g[12]]["yes"],ma[g[13]]["yes"],ma[g[14]]["yes"],ma[g[15]]["yes"],ma[g[16]]["no"],
               5,2,2,1,1,4,0,10,12))

# print(ip)
ip = ip.reshape(1,-1)
# print(ip)
pred = clf.predict(ip)
print('Student G3:',pred[0])

Student G3: 12.665523920085297